version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: riwimedicare_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: riwimedicare_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: riwimedicare_api
    restart: always
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: adminpassword
      DB_NAME: riwimedicare_db
      JWT_SECRET: super_secret_jwt_key
    depends_on:
      - db

volumes:
  postgres_data: